Add new constants
python-telegram-bot/python-telegram-bot pull request #2147
Opened 2020-10-15 11:26 UTC by NikitaPirate

2020-10-15 12:20 UTC, Bibo-Joshi requested changes
Thanks for the PR!

I did a bit of nitpicking. Please add the `is_*` thingies to `Chat`, too. Also, we'll need some unittests. Have a look at `tests/test_{user/chat}.py` some inspiration :) if you want to run one one single test for checking, if it works, you can use `pytest -k test_function_name`.

Finally, I feel like it would be cleaner to make the `is_*` thingies properties instead of attributes. While no one in the right mind would change the chats id after initialization, properties could still catch that and also that way it would be clearer that it's just a convenience thingy. So IMHO it should be something like [this](https://github.com/python-telegram-bot/python-telegram-bot/blob/3b4559dd95d14a4c9a9ca54237b5fe547386b666/telegram/bot.py#L351).

2020-10-15 12:20 UTC, Bibo-Joshi commented on telegram/constants.py
> +    ANONYMOUS_ADMIN_ID (:obj:`int`):777000
```suggestion
    ANONYMOUS_ADMIN_ID (:obj:`int`): ``777000``
```

2020-10-15 12:20 UTC, Bibo-Joshi commented on telegram/constants.py
> +    CHANNEL_FORWARDER_SERVICE_ID (:obj:`int`): 1087968824 (Telegram service that forwards messages
```suggestion
    CHANNEL_FORWARDER_SERVICE_ID (:obj:`int`): ``1087968824`` (Telegram service that forwards messages
```

Also this is the anonymous admin id and 777000 is the service chat ;) I'm not sure about the naming, though. 777000 is also the id of the chat that gives you your login PINs. imo naming ``SERVICE_CHAT_ID`` + the note that this is the one forwarding the messages to discussion groups is more concise.
But I'm not too passionate about it …

2020-10-15 12:20 UTC, Bibo-Joshi commented on telegram/user.py
> +        self.is_anonymous_admin = True if self.id == constants.ANONYMOUS_ADMIN_ID else False
```suggestion
        self.is_anonymous_admin = self.id == constants.ANONYMOUS_ADMIN_ID
```

2020-10-15 12:20 UTC, Bibo-Joshi commented on telegram/user.py
> +            True if self.id == constants.CHANNEL_FORWARDER_SERVICE_ID else False)
```suggestion
        self.is_channel_forwarder_service = self.id == constants.CHANNEL_FORWARDER_SERVICE_ID
```

2020-10-15 12:20 UTC, Bibo-Joshi commented on telegram/user.py
> +            Undocumented behavior.
```suggestion
            This behaviour is undocumented and might be changed by Telegram.
```

2020-10-15 20:21 UTC, Bibo-Joshi reviewed
Thanks, that looks good :) I left some minor reformulation suggestions. But I'd like @Poolitzer to review anyway, so he can decide about those.

2020-10-15 20:21 UTC, Bibo-Joshi commented on telegram/chat.py
> +        """:obj:`bool`: :obj:`True`, if it is chat with an anonymous admin.
```suggestion
        """:obj:`bool`: :obj:`True`, if this chat is with is the bot representing anonymous admins.
```

2020-10-15 20:21 UTC, Bibo-Joshi commented on telegram/chat.py
> +        """:obj:`bool`: :obj:`True`, if it is chat with the telegram service.
```suggestion
        """:obj:`bool`: :obj:`True`, if this chat is the Telegram service chat.
```

2020-10-15 20:21 UTC, Bibo-Joshi commented on telegram/constants.py
> +    SERVICE_CHAT_ID (:obj:`int`): ``777000`` (Telegram service)
```suggestion
    SERVICE_CHAT_ID (:obj:`int`): ``777000`` (Telegram service chat, that also acts as sender of channel posts forwarded to discussion groups)
```

2020-10-17 12:00 UTC, Poolitzer commented on telegram/chat.py
> +            This behaviour is undocumented and might be changed by Telegram. """
maybe call it convenience property? We are doing it like that in eg [user.py](https://github.com/python-telegram-bot/python-telegram-bot/blob/264b2c9c72691c5937b80e84e061c52dd2d8861a/telegram/user.py#L101)

2020-10-17 12:02 UTC, Poolitzer commented on telegram/constants.py
> +    ANONYMOUS_ADMIN_ID (:obj:`int`): ``1087968824``
explain where that happens :) Like user id in groups for anon admins

2020-10-17 12:02 UTC, Poolitzer requested changes
left two minor comments, thanks for the improvement!

2020-10-18 14:15 UTC, merged

2020-10-18 14:16 UTC, Bibo-Joshi commented
Thanks for the contribution!