Render-fixes for BP
python-telegram-bot/python-telegram-bot pull request #2253
Opened 2020-12-17 18:30 UTC by Bibo-Joshi

Gathering doc fixes to be merged before the next release

2020-12-27 01:55 UTC, mik-laj commented on telegram/ext/basepersistence.py
> +    * `meth:`get_bot_data`
It doesn't look good. Can you check it?

2020-12-27 13:47 UTC, TheShubhendra requested changes

2020-12-27 13:47 UTC, TheShubhendra commented on telegram/ext/basepersistence.py
> +    * `meth:`get_bot_data`
This change should be reverted

2021-01-31 14:42 UTC, Poolitzer approved these changes
looks good

2021-02-01 16:59 UTC, merged