Update docs & ignore edited channel posts
python-telegram-bot/python-telegram-bot pull request #2339
Opened 2021-01-26 19:19 UTC by Bibo-Joshi

See #2338, but I ended up changing more than the docs, so here is a standalone PR

* I did *not* list all the different update/handler types, as that's beyond the scope of the docs imho. Also, for the most updates it's rather obvious, which updates are associated with a chat/user/message id and which aren't.
* Instead I linked the FAQ, which can be more easily extended and also the wiki is the better place for elaborate explanations.
* Channel posts are ignored, see #487. This PR makes it also ignore *edited* channel posts, for completeness sake. Note that this is *not* a user facing change, as CH already ignores new posts, and hence a conversation that would be able to handle edited channel posts (i.e. `per_user=per_message=False`, `per_chat=True`)  can't even be started. Okay, yeah, if all of `per_user=per_chat=per_message=False`, then a CH can currenlty handle edited channel posts, but if someone uses that, they should overthink their design pattern …

2021-01-27 16:30 UTC, harshil21 commented on telegram/ext/conversationhandler.py
> +        ``ConversationHandler`` will only accept updates that a instances of (subclasses of)
```suggestion
        ``ConversationHandler`` will only accept updates that are instances of (subclasses of)
```

2021-01-31 16:14 UTC, Poolitzer requested changes
me talking english

2021-01-31 16:14 UTC, Poolitzer commented on telegram/ext/conversationhandler.py
> +        ``per_chat=True`` and ``update.callback_query.inline_message_id`` for ``per_chat=False``.
```suggestion
        ``ConversationHandler`` uses ``update.callback_query.message.message_id`` when
        ``per_chat=True`` and ``update.callback_query.inline_message_id`` when``per_chat=False``.
```

2021-01-31 17:33 UTC, Bibo-Joshi commented on telegram/ext/conversationhandler.py
> +        ``ConversationHandler`` will only accept updates that are instances of (subclasses of)
But …

```python
class Child(tg.Update):
    pass

assert isinstance(Child, Update) is False
```

2021-01-31 17:33 UTC, Bibo-Joshi commented on telegram/ext/conversationhandler.py
> +        ``per_chat=True`` and ``update.callback_query.inline_message_id`` for ``per_chat=False``.
```suggestion
        ``ConversationHandler`` uses ``update.callback_query.message.message_id`` when
        ``per_chat=True`` and ``update.callback_query.inline_message_id`` when ``per_chat=False``.
```

2021-01-31 17:38 UTC, Poolitzer commented on telegram/ext/conversationhandler.py
> +        ``ConversationHandler`` will only accept updates that are instances of (subclasses of)
sure, lets overcomplicate strings, you nitpicking german

```suggestion
        ``ConversationHandler`` will only accept updates that are instances (or subclasses) of
```

2021-01-31 17:43 UTC, Bibo-Joshi commented on telegram/ext/conversationhandler.py
> +        ``ConversationHandler`` will only accept updates that are instances of (subclasses of)
That … doesn't make it better  :D maybe 

```suggestion
        ``ConversationHandler`` will only accept updates that are (subclass-)instances of
```
? Or we just drop the note on subclasses. Should be clear enough, that `isinstance` is used …

2021-01-31 17:46 UTC, Poolitzer commented on telegram/ext/conversationhandler.py
> +        ``ConversationHandler`` will only accept updates that are instances of (subclasses of)
or that. I dont think it makes much of a difference, just wanted to improve the of use

2021-02-01 18:26 UTC, merged