Ignore classes on replace/insert_bot
python-telegram-bot/python-telegram-bot pull request #2523
Opened 2021-05-15 14:49 UTC by Bibo-Joshi

Closes #2513

### Checklist for PRs

- [x] `.. versionadded:: version` not necessary, this is more a bug fix than a change …
- [x] Created new or adapted existing unit tests

2021-05-15 17:24 UTC, harshil21 requested changes

2021-05-15 17:24 UTC, harshil21 commented on telegram/ext/basepersistence.py
> +        classes.
same

2021-05-15 17:24 UTC, harshil21 commented on telegram/ext/basepersistence.py
> +                'the docs of BasePersistence.replace_bot for more information.',
insert_bot

2021-05-16 08:00 UTC, Bibo-Joshi commented
Test failure apparently due to GH Actions currently having problems, see https://www.githubstatus.com
When that's resolved & we can rerun, I guess I'll merge. Thanks for the review @harshil21 !

2021-05-16 11:14 UTC, harshil21 approved these changes

2021-05-16 18:02 UTC, merged