Catch exceptions raised while copying __dict__/__slots__ in BasePersi…
python-telegram-bot/python-telegram-bot pull request #2564
Opened 2021-06-17 09:58 UTC by zeroone2numeral2

…stence.replace/insert_bot()

Also updated the docstrings to reflect the changes in behavior with unexpected errors

### Checklist for PRs

- [ ] Added `.. versionadded:: version`, `.. versionchanged:: version` or `.. deprecated:: version` to the docstrings for user facing changes (for methods/class descriptions, arguments and attributes)
- [ ] Created new or adapted existing unit tests
- [ ] Added myself alphabetically to `AUTHORS.rst` (optional)

2021-06-17 10:00 UTC, zeroone2numeral2 commented
I was looking at the contribution guidelines. Quiting:

> Add .. versionadded:: version, .. versionchanged:: version or .. deprecated:: version to the associated documentation of your changes, depending on what kind of change you made. This only applies if the change you made is visible to an end user. The directives should be added to class/method descriptions if their general behaviour changed and to the description of all arguments & attributes that changed.

I did made some changes to the docstring of the `replace_bot` and `insert_bot` methods, so I built the docs and looked for their docs source. But I can't find any `versionchanged` string. I'm not sure if I'm supposed to do something or not

2021-06-17 10:27 UTC, zeroone2numeral2 commented
Question about tests: I've added a `uuid.UUID` object  to `CustomClass`, which is immutable and would raise a `TypeError` in `insert/replace_bot`. I tried to run the tests as described in the contributions guidelines with `pytest -v`, but I'm a bit lost: the test for `test_persistence.py` failed with the following output: https://nekobin.com/loqazeruxi

I'm not entirely sure how I should update the test

2021-06-17 18:52 UTC, Bibo-Joshi requested changes
Thanks for the PR!

Regarding docstrings: Those look fine, shouldn't be a problem to build them 👌 
Regarding tests: I forgot that pytest treats warnings as errors if not handled otherwise … On a  closer look I see that we have a for unpickable objects test [here](https://github.com/python-telegram-bot/python-telegram-bot/blob/52ce03929b3255eade1081b2ee6fa278708dbef9/tests/test_persistence.py#L643-L690). You can copy that and replace `lock` with `uuid` (you can skip the `CustomClass` part and revert your current changes to the tests)

Also, `pre-commit` complains about a few things. Please make sure to run `pre-commit install` on your machine so that `pre-commit` can run on every commit. You can also have it run manually via `pre-commit run`. Have a look at the contribution guide for more details :)

2021-06-17 18:52 UTC, Bibo-Joshi commented on telegram/ext/basepersistence.py
> +                f'Parsing of an object failed with the following exception: {exception_description}. '
just `f'... {e}'` should work, too, shouldn't it? same below

2021-06-18 14:11 UTC, harshil21 commented on telegram/ext/basepersistence.py
> +                f'See the docs of BasePersistence.insert_bot for more information.',
```suggestion
                f'See the docs of BasePersistence.replace_bot for more information.',
```

2021-06-18 18:05 UTC, Bibo-Joshi commented
Except for the typo, this looks good to me :)

2021-06-20 20:14 UTC, merged

2021-06-20 20:14 UTC, Bibo-Joshi commented
Thanks for the contribution @zeroone2numeral2 :)

2021-06-21 06:40 UTC, zeroone2numeral2 commented
Thanks @harshil21 for the commit! I've been busy during the weekend

And thanks for the merge :)