Fix Bot.copy_message
python-telegram-bot/python-telegram-bot pull request #2651
Opened 2021-09-07 15:23 UTC by DonalDuck004

When you pass "" as a caption to this method, the caption is not sent to the Telegram API, because the if on line 5299 does not allow it to insert it in the dict of data to be sent to the Telegram API

2021-09-07 15:34 UTC, Poolitzer commented
Hm. How does this result in unwanted behavior?

2021-09-07 15:38 UTC, DonalDuck004 commented
> Hm. How does this result in unwanted behavior? Can you delete an existing caption this way?

Yes, this change allows you to remove the caption

2021-09-07 15:40 UTC, Poolitzer commented
Ah. Great catch. Can you write a test verifying that it works now?

2021-09-07 15:43 UTC, DonalDuck004 commented
Yes, now I try

2021-09-07 15:56 UTC, DonalDuck004 commented
Code: https://pastebin.com/FsZJVNQb
Results: https://telegra.ph/file/87592e9b91f6238c7c2c9.jpg

2021-09-07 16:04 UTC, Poolitzer commented
Oh no. Thats fine, I believed you that your change was working in the first place :D

I asked for a unitest, can you do that? We have them in the `tests` directory.

2021-09-07 16:28 UTC, DonalDuck004 commented
Sorry, can you explain better? 😅
I should run something with my change?

2021-09-07 17:36 UTC, Bibo-Joshi commented
What pool means is that we have automated [unit tests](https://en.m.wikipedia.org/wiki/Unit_testing), which life in the `tests` directory. For this specifically, the file `test_bot.py` will be the place to work - you can search for unit tests on `copy_message` in there. Please also have a look the [contribution guide](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/.github/CONTRIBUTING.rst) which explains how to run the tests.
If you're having trouble with the tests feel free to ping us here - tests are scary on the first encounter :D

2021-09-07 18:03 UTC, Andredego commented
Como faça o bot de telegram e instragan e kwai e tik tok

Em ter, 7 de set de 2021 12:24, DonalDuck004 ***@***.***>
escreveu:

> When you pass "" as a caption to this method, the caption is not sent to
> the Telegram API, because the if on line 5299 does not allow it to insert
> it in the dict of data to be sent to the Telegram API
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/python-telegram-bot/python-telegram-bot/pull/2651
> Commit Summary
>
>    - Fix Bot.copy_message
>
> File Changes
>
>    - *M* telegram/bot.py
>    <https://github.com/python-telegram-bot/python-telegram-bot/pull/2651/files#diff-ca0526e3005b92a3844ee53d68688fe5a8c438332365a0efc3275a814cca5008>
>    (2)
>
> Patch Links:
>
>    -
>    https://github.com/python-telegram-bot/python-telegram-bot/pull/2651.patch
>    -
>    https://github.com/python-telegram-bot/python-telegram-bot/pull/2651.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/python-telegram-bot/python-telegram-bot/pull/2651>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVQSSDQFE7ZA3MA4HMG73U3UAYVCLANCNFSM5DSUKJ2A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-07 18:03 UTC, DonalDuck004 commented
Ok, thanks for the help

2021-09-07 18:37 UTC, DonalDuck004 commented
> Ah. Grande cattura. Puoi scrivere un test per verificare che funzioni ora?

[pytest_result.txt](https://github.com/python-telegram-bot/python-telegram-bot/files/7123665/pytest_result.txt)
It's correct? I believe I did it correctly

2021-09-07 19:20 UTC, DonalDuck004 commented
> Ah. Great catch. Can you write a test verifying that it works now?

Is this correct? https://pastebin.com/Af9fPsfH


Result:
================================================= test session starts =================================================
platform win32 -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- c:\users\myUser\appdata\local\programs\python\python39\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\myUser\Desktop\python-telegram-bot-master, configfile: setup.cfg
plugins: Faker-5.4.0, flaky-3.7.0
collected 6 items

tests/test_bot.py::TestBot::test_copy_message[<b>Test</b>-True] PASSED                                           [ 16%]
tests/test_bot.py::TestBot::test_copy_message[<b>Test</b>-False] PASSED                                          [ 33%]
tests/test_bot.py::TestBot::test_copy_message[-True] PASSED                                                      [ 50%]
tests/test_bot.py::TestBot::test_copy_message[-False] PASSED                                                     [ 66%]
tests/test_bot.py::TestBot::test_copy_message[None-True] PASSED                                                  [ 83%]
tests/test_bot.py::TestBot::test_copy_message[None-False] PASSED                                                 [100%]

================================================== 6 passed in 2.22s ==================================================

2021-09-08 05:51 UTC, Bibo-Joshi requested changes
looks good except for the failing pre-commit test :) I you like to, we could add another test in the style of `test_copy_message_without_reply`, which actually checks the result on the copied message instad of just checking that we pass the correct parameters to TG, but IMO that's optional.

2021-09-08 05:51 UTC, Bibo-Joshi commented on tests/test_bot.py
> +
trailing whitespace

2021-09-08 05:51 UTC, Bibo-Joshi commented on tests/test_bot.py
> +
trailing whitespace

2021-09-08 14:45 UTC, DonalDuck004 commented on tests/test_bot.py
> +
Done

2021-09-09 05:50 UTC, merged

2021-09-09 05:50 UTC, Bibo-Joshi commented
Thanks for the contribution!