Fix from attribute
python-telegram-bot/python-telegram-bot pull request #2719
Opened 2021-10-08 20:29 UTC by SimonDamberg

- `TelegramObject.__getitem__` now raises `KeyError` instead of returning `None`, and a special case is made for `obj['from']` to look up `obj['from_user']`. 
- Removed `__getitem__` override from `Message`
- Test for Message changed to check for `KeyError` instead of `None`.

### Checklist for PRs

- [ ] Added `.. versionadded:: version`, `.. versionchanged:: version` or `.. deprecated:: version` to the docstrings for user facing changes (for methods/class descriptions, arguments and attributes)
- [x] Created new or adapted existing unit tests
- [x] Added myself alphabetically to `AUTHORS.rst` (optional)

2021-10-09 14:30 UTC, Bibo-Joshi commented
> There's a pre-commit test failing. Can you add a pylint ignore on that line? see the other places in the code on how to add a pylint ignore.

rather just do what pylint suggests to do ;)

2021-11-13 20:15 UTC, Bibo-Joshi commented
@SimonDamberg are you still interested in finishing the PR? :)

2021-11-16 18:43 UTC, SimonDamberg commented
A lot of things came up at school and job. If someone wants to clean up and finish, feel free to do so :)

2021-11-21 11:19 UTC, harshil21 requested changes

2021-11-21 11:19 UTC, harshil21 commented on telegram/_telegramobject.py
> +    Objects of this type a subscriptable with strings, where ``telegram_object[attribute_name]`` is
```suggestion
    Objects of this type are subscriptable with strings, where ``telegram_object[attribute_name]`` is
```

2021-11-21 11:19 UTC, harshil21 commented on telegram/_telegramobject.py
> +    the appropriate name, a :class:`KeyError` will be raised.
```suggestion
    the appropriate name, a :exc:`KeyError` will be raised.
```
I think this plays in better with intersphinx

2021-11-21 11:39 UTC, harshil21 approved these changes

2021-11-21 12:36 UTC, merged

2021-11-21 12:36 UTC, Bibo-Joshi commented
Thanks for getting this started @SimonDamberg :)