Adding support for self signed certificate
python-telegram-bot/python-telegram-bot pull request #3088
Opened 2022-06-09 10:03 UTC by Bouk250

### Checklist for PRs

- [ ] Added `.. versionadded:: version`, `.. versionchanged:: version` or `.. deprecated:: version` to the docstrings for user facing changes (for methods/class descriptions, arguments and attributes)
- [ ] Created new or adapted existing unit tests
- [ ] Documented code changes according to the [CSI standard](https://standards.mousepawmedia.com/en/stable/csi.html)
- [ ] Added myself alphabetically to `AUTHORS.rst` (optional)
- [ ] Added new classes & modules to the docs and all suitable `__all__` s

### If the PR contains API changes (otherwise, you can delete this passage)

* New classes:
    - [ ] Added `self._id_attrs` and corresponding documentation
    - [ ] `__init__` accepts `**_kwargs`
    
* Added new shortcuts:
    - [ ] In `Chat` & `User` for all methods that accept `chat/user_id`
    - [ ] In `Message` for all methods that accept `chat_id` and `message_id`
    - [ ] For new `Message` shortcuts: Added `quote` argument if methods accepts `reply_to_message_id`
    - [ ] In `CallbackQuery` for all methods that accept either `chat_id` and `message_id` or `inline_message_id`
    
* If relevant:

    - [ ] Added new constants at `telegram.constants` and shortcuts to them as class variables
    - [ ] Link new and existing constants in docstrings instead of hard coded number and strings
    - [ ] Add new message types to `Message.effective_attachment`
    - [ ] Added new handlers for new update types
      - [ ] Add the handlers to the warning loop in the `ConversationHandler`
    - [ ] Added new filters for new message (sub)types
    - [ ] Added or updated documentation for the changed class(es) and/or method(s)
    - [ ] Added or updated `bot_methods.rst`
    - [ ] Updated the Bot API version number in all places: `README.rst` and `README_RAW.rst` (including the badge), as well as `telegram.constants.BOT_API_VERSION`
    - [ ] Added logic for arbitrary callback data in `tg.ext.Bot` for new methods that either accept a `reply_markup` in some form or have a return type that is/contains `telegram.Message`

2022-06-09 10:04 UTC, Bibo-Joshi commented
Hi. can you explain your use case for this?

2022-06-09 10:09 UTC, Bouk250 commented
Hi, yes.

My network connection pass over gateway with self signed ssl certificate.
The problem is when i try to set up bot i gon an exception:
SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')

So I added a verify function to the application builder for adding support to ssl certfile. with pem file path ...

2022-06-09 10:16 UTC, Bibo-Joshi commented
> My network connection pass over gateway with self signed ssl certificate. 

Sorry, I don't quite understand. what kind of gateway? I'm asking because I'd like to evaluate how specific to your use case this issue is, i.e. if the use case is broad enough to add it to the library :)

2022-06-09 10:18 UTC, Poolitzer commented
Im sorry what is happening here. I used https://docs.python-telegram-bot.org/en/v20.0a0/telegram.ext.application.html#telegram.ext.Application.run_webhook with the cert and key option + self signed certificate just fine before the alpha release. Is there a traceback happening when you use that?

2022-06-09 10:20 UTC, Poolitzer commented
@Bibo-Joshi ohh the git diff hid that from my eyes, im sorry

2022-06-09 11:08 UTC, Bouk250 commented
> Sorry, I don't quite understand. what kind of gateway? I'm asking because I'd like to evaluate how specific to your use case this issue is, i.e. if the use case is broad enough to add it to the library :)

For example it's can happen when the bot connection pass over company network, sub-network, proxy...

2022-06-19 14:00 UTC, Bibo-Joshi requested changes
> For example it's can happen when the bot connection pass over company network, sub-network, proxy...

Okay, that sounds somewhat reasonable to me and I'd be willing to accept a contribution for this.

I left a number of review comments below. In addition, please make sure to cover all applicable items of the pr-check list + everything mentioned in the [contribution guide](https://docs.python-telegram-bot.org/en/v20.0a1/contributing.html). If you're having troubles with adding & adapting unit tests, feel free to reach out here or in the [dev group](https://t.me/pythontelegrambotchannel/105).

2022-06-19 14:00 UTC, Bibo-Joshi commented on telegram/request/_httpxrequest.py
> +
please remove

2022-07-07 21:19 UTC, Bibo-Joshi commented
I'll close this due to inactivity for now. If you'd like to pick up this PR, feel free to comment/open a new pr :)

2022-07-07 21:19 UTC, closed without merging