Note on editing with reply markups
python-telegram-bot/python-telegram-bot pull request #3121
Opened 2022-06-25 22:31 UTC by ExalFabu

Hi, i would like to help and contribute on #3111 
Following the [official documentation](https://core.telegram.org/bots/api#updating-messages), the methods i updated are: 
- `Bot.edit_message_text`
- `Bot.edit_message_caption`
- `Bot.edit_message_media`

I am not adding the note on the method `Bot.edit_message_reply_markup` since I don't think it makes sense in the first place, I hope I'm not wrong.

Screenshots:
![edit_message_text](https://user-images.githubusercontent.com/53974096/175792167-b3b964e7-06d4-4b66-a41d-4b717bdd9ea2.png)

![edit_message_caption](https://user-images.githubusercontent.com/53974096/175792198-9a82cbda-e7b4-49ba-b128-767114fb1d99.png)

![edit_message_media](https://user-images.githubusercontent.com/53974096/175792208-6dd31af6-417d-48bb-b88b-fd181c18f2fe.png)

2022-06-26 13:29 UTC, Bibo-Joshi requested changes
Hi, thanks for the PR! I left two comments below.

> I am not adding the note on the method `Bot.edit_message_reply_markup` since I don't think it makes sense in the first place, I hope I'm not wrong.

Why do yout think that it doesn't make sense to have the note there? people can still try to edit messages without reply markup of with `ReplyKeyboardMarkup` …

2022-06-26 13:29 UTC, Bibo-Joshi commented on telegram/_bot.py
> +            :paramref:`reply_markup` or with inline keyboards
```suggestion
            :attr:`telegram.Message.reply_markup` or with inline keyboards.
```

Same in the other places

2022-06-26 13:29 UTC, Bibo-Joshi commented on telegram/_bot.py
> +            Please note, that it is currently only possible to edit messages without
```suggestion
            It is currently only possible to edit messages without
```

to keep it unified :)

2022-06-26 16:06 UTC, ExalFabu commented
> Why do yout think that it doesn't make sense to have the note there? people can still try to edit messages without reply markup of with `ReplyKeyboardMarkup` …

As i understood it, the meaning of the note specifies that you can only edit the text of a message if it does not contain a reply markup, since that method is supposed to be used to edit the reply markup I thought it was kind of unnecessary. 
Anyway I added it since I don't disagree with the "better safe than sorry" philosophy

2022-06-27 16:42 UTC, merged

2022-06-27 16:42 UTC, Bibo-Joshi commented
Thank you for the contribution! :)