Add more crossrefs to docstrings
python-telegram-bot/python-telegram-bot pull request #3398
Opened 2022-11-29 12:04 UTC by lemontree210

closes #3110 (this is the final one of the updates that close this issue)

2022-11-29 16:13 UTC, lemontree210 commented
I think I found all there was to find in `Bot`. Are there any other classes I should inspect?

2022-11-30 08:55 UTC, harshil21 approved these changes
Bot is the most important class for references so I'm fine with this 👍🏽

2022-11-30 14:12 UTC, Bibo-Joshi requested changes
just one comment :) If @harshil21 and @lemontree210 are done with this PR otherwise, I'm happy to merge and close #3110 👍

2022-11-30 14:12 UTC, Bibo-Joshi commented on telegram/_bot.py
> +        .. seealso:: :meth:`telegram.ext.Updater.start_webhook`
App.run_webhook as well :)

2022-11-30 14:24 UTC, lemontree210 commented on telegram/_bot.py
> +        .. seealso:: :meth:`telegram.ext.Updater.start_webhook`
Done

2022-11-30 14:46 UTC, merged