Use pytest's `--lf` and `--lfnf` to stabilize tests
python-telegram-bot/python-telegram-bot pull request #3631
Opened 2023-03-25 23:01 UTC by harshil21

Closes #3626

2023-03-26 19:51 UTC, Bibo-Joshi reviewed
Thanks for the PR!

Just for future reference: We can see the effect of the changes in the job runs

* https://github.com/python-telegram-bot/python-telegram-bot/actions/runs/4521712977/jobs/7963608524?pr=3631
* https://github.com/python-telegram-bot/python-telegram-bot/actions/runs/4521712977/jobs/7963608648?pr=3631

Would you mind also applying this to the "test without opt. deps" section? 🤔

2023-03-27 20:01 UTC, Bibo-Joshi requested changes

2023-03-27 20:01 UTC, Bibo-Joshi commented on .github/workflows/test.yml
> +          pytest -v --cov -k "${TO_TEST}" --lf --lfnf=none
```suggestion
          pytest -v --cov --cov-append -k "${TO_TEST}" --lf --lfnf=none
```

2023-03-27 20:26 UTC, harshil21 commented on .github/workflows/test.yml
> +          pytest -v --cov -k "${TO_TEST}" --lf --lfnf=none
sneaky, that's why coverage was failing

2023-04-01 20:35 UTC, merged