Remove Bot API Related Deprecations
python-telegram-bot/python-telegram-bot pull request #3858
Opened 2023-08-24 21:07 UTC by Bibo-Joshi

ToDo:

- [ ] https://github.com/python-telegram-bot/python-telegram-bot/projects/9#card-88599701
- [ ] https://github.com/python-telegram-bot/python-telegram-bot/projects/9#card-87927012
- [ ] Adjust tests

2023-08-28 12:29 UTC, harshil21 requested changes
damn that was a lot of code. Doc build is failing btw.

2023-08-28 12:29 UTC, harshil21 commented on telegram/_message.py
>              |custom_emoji_md1_deprecation|
"deprecation" -> something else?

2023-08-28 12:29 UTC, harshil21 commented on tests/test_official.py
> +BACKWARDS_COMPAT_KWARGS = {}
clean 🔥

2023-09-02 13:14 UTC, lemontree210 reviewed
Amazing effort 👏🏻

2023-09-02 15:47 UTC, Bibo-Joshi commented on telegram/_files/_basethumbedmedium.py
> -        thumb (:class:`telegram.PhotoSize`, optional): Thumbnail as defined by sender.
TBH I didn't bother b/c it's a private class. I don't really know why it has a docstring in the first place :D

2023-09-03 12:23 UTC, merged