Add `JobQueue.scheduler_configuration` and add corresponding warnings
python-telegram-bot/python-telegram-bot pull request #3913
Opened 2023-10-01 11:09 UTC by Bibo-Joshi

Proposal for closing #3837

Makes the config values used by `JobQueue` publically accessible so that users can use them in addition to their custom values. Also adds warnigs that explain what this is about.

@rejedai, would you mind also having a look at this, given that you reported the issue?

- [x] Added ``.. versionadded:: NEXT.VERSION``, ``.. versionchanged:: NEXT.VERSION`` or ``.. deprecated:: NEXT.VERSION`` to the docstrings for user facing changes (for methods/class descriptions, arguments and attributes)
- [x] Created new or adapted existing unit tests
- [x] Documented code changes according to the `CSI standard <https://standards.mousepawmedia.com/en/stable/csi.html>`__
- ~Added myself alphabetically to ``AUTHORS.rst`` (optional)~
- ~Added new classes & modules to the docs and all suitable ``__all__`` s~
-  [x] Checked the `Stability Policy <https://docs.python-telegram-bot.org/stability_policy.html>`_ in case of deprecations or changes to documented behavior

2023-10-03 21:31 UTC, lemontree210 requested changes
just a micro-typo

2023-10-03 21:31 UTC, lemontree210 commented on telegram/ext/_jobqueue.py
> +                Alternatively, you cas also use methods like
```suggestion
                Alternatively, you can also use methods like
```

2023-10-03 21:31 UTC, lemontree210 commented on telegram/ext/_jobqueue.py
> +            Alternatively, you cas also use methods like
```suggestion
            Alternatively, you can also use methods like
```

2023-10-06 21:41 UTC, lemontree210 commented
Please make sure you delete me from authors before merging, otherwise I'll be known for co-authoring a commit to master just because I changed one letter :)

2023-10-16 07:36 UTC, harshil21 reviewed
Changes look good to me. However codecov is complaining about untested lines. Is it really not possible to test them?

2023-10-16 07:39 UTC, harshil21 commented
macos py3.12 test consistently failing, but the errors aren't exactly related to this PR?

2023-10-16 17:56 UTC, Bibo-Joshi commented
Mh, codecov doesn't complain [in their UI](https://app.codecov.io/gh/python-telegram-bot/python-telegram-bot/pull/3913/blob/telegram/ext/_jobqueue.py) and I'm also pretty certain that the tests cover everything. Maybe the annotations just stuck from the initial runs …

TBH I don't recall why the macos tests failed. Might have been due to codecov upload failure. I'm rerunning.

2023-10-16 18:15 UTC, harshil21 approved these changes
alright, test pass and code looks covered by the tests 👍🏽

2023-10-16 18:25 UTC, merged