WIP: Add `Bot.do_api_request`
python-telegram-bot/python-telegram-bot pull request #4084
Opened 2024-01-28 16:43 UTC by Bibo-Joshi

Closes #4053

Testing still missing

2024-01-29 16:16 UTC, Poolitzer requested changes
LGTM just one phrasing request out of pride

2024-01-29 16:16 UTC, Poolitzer commented on telegram/_bot.py
> +        by the python-telegram-bot library.
```suggestion
        by this library.
```

2024-01-29 16:16 UTC, Poolitzer commented on telegram/_utils/strings.py
> +    return components[0] + "".join(x.title() for x in components[1:])
I am waiting for some weird method to break this xD

2024-02-07 12:14 UTC, clot27 commented on telegram/error.py
> +            .. versionadded:: 20.0
Wrong versionadded directive

2024-02-07 12:20 UTC, clot27 reviewed
Great addition! just few nitpicks

2024-02-07 12:20 UTC, clot27 commented on telegram/error.py
> +            .. versionadded:: 20.0
Wrong versionadded directive

2024-02-07 12:20 UTC, clot27 commented on tests/test_bot.py
> +    print(arg_values)
can be removed now ig

2024-02-07 21:35 UTC, merged