Api 7.3 docs
python-telegram-bot/python-telegram-bot pull request #4246
Opened 2024-05-09 07:43 UTC by Bibo-Joshi

Several documentation updates from API 7.3. See the API changelog as well as https://t.me/bot_api_changes/133

2024-05-09 22:46 UTC, harshil21 requested changes
https://t.me/bot_api_changes/134 can also be added

2024-05-09 22:46 UTC, harshil21 commented on telegram/_bot.py
`send_location.live_period`, `IQRL.live_period`, and  `InputLocationMessageContent.live_period` docstring also changed - "Period in seconds during which the location will be updated (see <a href="https://telegram.org/blog/live-locations">Live Locations</a>, should be between 60 and 86400, or 0x7FFFFFFF for live locations that can be edited indefinitely."

2024-05-10 15:43 UTC, Bibo-Joshi commented on telegram/_bot.py
That has already been partially added in #4247 that's why I didn.t want to do it here. We'll also need a new constant for that

2024-05-12 11:45 UTC, aelkheir commented on telegram/_business.py
> +    This object Contains information about the location of a Telegram Business account.
```suggestion
    This object contains information about the location of a Telegram Business account.
```
Notification falsely says "requested your review", so found this :)

2024-05-18 04:42 UTC, merged