API 7.4
python-telegram-bot/python-telegram-bot pull request #4276
Opened 2024-05-28 13:13 UTC by harshil21

Central PR which will gather all PRs from api-7.4-feature

Closes #4275 .

- [ ] PRS to mention: 

### Checklist

- [ ] Added ``.. versionadded:: NEXT.VERSION``, ``.. versionchanged:: NEXT.VERSION`` or ``.. deprecated:: NEXT.VERSION`` to the docstrings for user facing changes (for methods/class descriptions, arguments and attributes)
- [ ] Created new or adapted existing unit tests
- [ ] Documented code changes according to the `CSI standard <https://standards.mousepawmedia.com/en/stable/csi.html>`__
- [ ] Added myself alphabetically to ``AUTHORS.rst`` (optional)
- [ ] Added new classes & modules to the docs and all suitable ``__all__`` s
- [ ] Checked the `Stability Policy <https://docs.python-telegram-bot.org/stability_policy.html>`_ in case of deprecations or changes to documented behavior

**If the PR contains API changes (otherwise, you can ignore this passage)**

- [ ] Checked the Bot API specific sections of the [Stability Policy](https://docs.python-telegram-bot.org/stability_policy.html)

- New classes:

   - [ ] Added ``self._id_attrs`` and corresponding documentation
   - [ ] ``__init__`` accepts ``api_kwargs`` as kw-only

- Added new shortcuts:

   - [ ]  In :class:`~telegram.Chat` & :class:`~telegram.User` for all methods that accept ``chat/user_id``
   - [ ]  In :class:`~telegram.Message` for all methods that accept ``chat_id`` and ``message_id``
   - [ ]  For new :class:`~telegram.Message` shortcuts: Added ``do_quote`` argument if methods accepts ``reply_to_message_id``
   - [ ] In :class:`~telegram.CallbackQuery` for all methods that accept either ``chat_id`` and ``message_id`` or ``inline_message_id``

-  If relevant:

   - [ ] Added new constants at :mod:`telegram.constants` and shortcuts to them as class variables
   - [ ] Link new and existing constants in docstrings instead of hard-coded numbers and strings
   - [ ]  Add new message types to :attr:`telegram.Message.effective_attachment`
   - [ ] Added new handlers for new update types
   - [ ] Add the handlers to the warning loop in the :class:`~telegram.ext.ConversationHandler`
   - [ ] Added new filters for new message (sub)types
   - [ ]  Added or updated documentation for the changed class(es) and/or method(s)
   - [ ] Added the new method(s) to ``_extbot.py``
   - [ ] Added or updated ``bot_methods.rst``
   - [ ] Updated the Bot API version number in all places: ``README.rst`` and ``README_RAW.rst`` (including the badge), as well as ``telegram.constants.BOT_API_VERSION_INFO``
   - [ ] Added logic for arbitrary callback data in :class:`telegram.ext.ExtBot` for new methods that either accept a ``reply_markup`` in some form or have a return type that is/contains :class:`~telegram.Message`

2024-05-30 05:29 UTC, harshil21 commented
not sure why `test_meta` is failing on 3.12 (setuptools is missing somehow), probably some kind of caching issue?

2024-05-30 05:31 UTC, Bibo-Joshi commented
@harshil21 Its failing on master as well. Maybe we&#x27;ll have to ensure installing setup tools in the CI

2024-06-01 21:14 UTC, Poolitzer requested changes
.

2024-06-01 21:14 UTC, Poolitzer commented on telegram/_inline/inlinekeyboardbutton.py
> +            be launched when the user presses the button
```suggestion
            be launched when the user presses the button.
```

2024-06-01 21:14 UTC, Poolitzer commented on telegram/_inline/inputinvoicemessagecontent.py
> +            user's shipping address to complete the order. Ignored for payments in |tg_stars|
```suggestion
            user's shipping address to complete the order. Ignored for payments in |tg_stars|.
```

2024-06-02 00:36 UTC, harshil21 commented on telegram/_bot.py
> +                majority of currencies). Defaults to ``0``. Not supported for payment in |tg_stars|
yea that period takes it over 100 chars that's why I didn't put it lmao

2024-06-03 17:39 UTC, merged