Add `adjust_message_entities_to_utf_16` utility
python-telegram-bot/python-telegram-bot pull request #4323
Opened 2024-06-24 13:55 UTC by Antares0982

add  `adjust_message_entities_to_utf_16` for #4319

2024-06-24 14:00 UTC, Antares0982 commented
Is there anything else should be add/changed?

2024-06-26 19:29 UTC, Bibo-Joshi requested changes
Hi, thank you very much for the PR! I left a number of comments. The overall logic is fine - thanks for catching the necessity for sorting! - but there are some things that can be improved :)

2024-06-26 19:29 UTC, Bibo-Joshi commented on telegram/_messageentity.py
> +        #         ^^^^   ^^^^^^             ^^^
it looks like the marking does not align. please make sure that this renders correctly in the html docs

2024-06-26 19:29 UTC, Bibo-Joshi commented on telegram/_messageentity.py
> +        # utf16_lengths[indexes_map[offset]] = len(text[:offset].encode("utf-16-le")) // 2
this comment is not particularly helpful. A code comment should explain what the meaning of the code is or why it is done. In this case, the meaning of the code would be something like `for each split_mark in unicode-space it stores the corresponding split_mark in utf_16-space`

2024-06-26 19:29 UTC, Bibo-Joshi commented on telegram/_messageentity.py
> +        indexes_map = {cut_offset: i for i, cut_offset in enumerate(offsets_list)}
I think this map is superflous - all you need is a mapping from unidoce-positions to utf_16-positions. So something like 

```python
position_mapping: Dict[int, int] = {}
for split_mark in split_marks:
    # do computation
    position_mapping[split_mark] = accumulated_length
```

should already do the trick

2024-06-26 19:29 UTC, Bibo-Joshi commented on telegram/_messageentity.py
> +            )
new_entity = copy.copy(entity)

```suggestion
            new_entity = copy.copy(entity)
            with new_entity._unfreeze():
                new_entity.offset = translated_offset
                new_entity.length = translated_length
```

`._unfreeze()` is an internal helper that allows us to override attributes after initialization if required.
Donig it this way prevents that we forget adding new arguments if they are added to `MessageEntity` :)

2024-06-26 19:29 UTC, Bibo-Joshi commented on tests/test_messageentity.py
> +    def test_fix_utf16(self):
please move to before `test_equality`

2024-06-26 19:29 UTC, Bibo-Joshi commented on telegram/_messageentity.py
> +            List[:class:`telegram.MessageEntity`]: Sequence of entities with offset and length
```suggestion
            Sequence[:class:`telegram.MessageEntity`]: Sequence of entities with offset and length
```

2024-07-01 18:21 UTC, Bibo-Joshi requested changes
Thanks for the updates! Left some more comments, mostly about documentation :)
Please don't force-push additional changes, as that makes it hard to see what which parts I've already reviewed.

2024-07-01 18:21 UTC, Bibo-Joshi commented on telegram/_messageentity.py
> +            If they are calculated using the Unicode string (`str` object), errors may occur
```suggestion
            If they are calculated using the Unicode string (:obj:`str` object), errors may occur
```

2024-07-01 18:21 UTC, Bibo-Joshi commented on telegram/_messageentity.py
> +        .. code-block:: python
can you indent this so that it's part of the "Example" admonition?

2024-07-01 18:21 UTC, Bibo-Joshi commented on telegram/_messageentity.py
> +            entities from Unicode to UTF-16 space. The `unicode_entities` are calculated in
```suggestion
            entities from Unicode to UTF-16 space. The ``unicode_entities`` are calculated in
```

2024-07-01 18:21 UTC, Bibo-Joshi commented on telegram/_messageentity.py
> +            `Plane (Unicode) <https://en.wikipedia.org/wiki/Plane_(Unicode)>`.
```suggestion
            For more information, see `Unicode <https://en.wikipedia.org/wiki/Unicode>`_ and
            `Plane (Unicode) <https://en.wikipedia.org/wiki/Plane_(Unicode)>`_.
```

2024-07-01 18:21 UTC, Bibo-Joshi commented on telegram/_messageentity.py
> +        Unicode (`str`) to UTF-16 (`utf-16-le` encoded `bytes`).
```suggestion
        Unicode (:obj:`str`) to UTF-16 (``utf-16-le`` encoded :obj:`bytes`).
```

2024-07-01 18:21 UTC, Bibo-Joshi commented on telegram/_messageentity.py
> +        offsets_list = sorted(
I still find the usage of "offset" misleading both here and below. Please use change to "position"

2024-07-01 18:21 UTC, Bibo-Joshi commented on telegram/_messageentity.py
> +        according_utf16_lengths: List[int] = []
I see no need for this helper variable. You can directly write the caculated postiions into "~offset~position_translation" as explained in https://github.com/python-telegram-bot/python-telegram-bot/pull/4323#discussion_r1655410569

2024-07-01 21:19 UTC, harshil21 commented on tests/test_messageentity.py
> +        import random
please import at that the top of the module

2024-07-01 21:19 UTC, harshil21 commented on telegram/_messageentity.py
> +
```suggestion

        .. versionadded:: NEXT.VERSION
```
missing versionadded (please check my indentation)

2024-07-05 14:14 UTC, Bibo-Joshi approved these changes
Thanks for the additional updates! LGTM now :) If @harshil21 approves as well, we can merge.

2024-07-05 23:33 UTC, harshil21 requested changes
one last doc fix

2024-07-05 23:33 UTC, harshil21 commented on telegram/_messageentity.py
> +            entities (List[:class:`telegram.MessageEntity`]): Sequence of entities
```suggestion
            entities (Sequence[:class:`telegram.MessageEntity`]): Sequence of entities
```

2024-07-06 14:08 UTC, merged

2024-07-06 14:08 UTC, Bibo-Joshi commented
Thank you very much for the nice contribution!