Bump ruff and add new rules
python-telegram-bot/python-telegram-bot pull request #4329
Opened 2024-06-28 04:12 UTC by harshil21

wake up, new ruff just dropped! 

new rules added:

- print: https://github.com/python-telegram-bot/python-telegram-bot/pull/4311#discussion_r1657902724
- "furb": https://docs.astral.sh/ruff/rules/#refurb-furb

2024-06-28 20:06 UTC, Bibo-Joshi approved these changes

2024-06-28 20:07 UTC, Bibo-Joshi requested changes
Upsie, no, pre-commit is failing I should not approve that :D

2024-06-28 23:58 UTC, harshil21 commented
> Upsie, no, pre-commit is failing I should not approve that :D

the ruff fix for job queue is probably going to break the type completeness again, do you want to ignore it?

2024-06-29 05:21 UTC, Bibo-Joshi commented on examples/passportbot.py
> +            logger.info("Phone: %s", data.phone_number)
Huh, first time I see this security feature doing something:D

2024-06-30 16:02 UTC, Bibo-Joshi approved these changes
Anything left from your side?

2024-06-30 16:16 UTC, harshil21 commented
all good

2024-06-30 16:22 UTC, merged