Docs fix/add introductory paragraphs to subsections
python-telegram-bot/python-telegram-bot pull request #4389
Opened 2024-07-18 05:01 UTC by mohdyusuf2312

### Description

This pull request adds introductory paragraphs to several sections in the PTB documentation and updates the "More info on xy" links to point to the PTB docs where appropriate.

### Changes Made

- Added introductory paragraphs to the Payments, Passport, Games, Inline Mode, Stickers, and Available Types sections.
- Updated "More info on xy" links to point to relevant sections in the PTB docs.
- Added my name to the `AUTHORS.rst` file.

### Issue Addressed

docs/fix #4380 

### Available Types section before
![image](https://github.com/user-attachments/assets/772d696f-9cdf-4e6a-8fa5-c952ac3d6f44)
### Available Types section after
![image](https://github.com/user-attachments/assets/29369da5-5ab6-489e-be83-5dd02912e09c)

### Stickers section before
![image](https://github.com/user-attachments/assets/a59cc056-0ae2-49c8-ac38-cea9aa1aeb2d)
### Stickers section after
![image](https://github.com/user-attachments/assets/0d8992d1-9f10-44b1-9ef0-b329f988db43)

### Inline Mode section before
![image](https://github.com/user-attachments/assets/acdf765e-b09a-4c3c-958c-29bc3f1a9a29)
### Inline Mode section after
![image](https://github.com/user-attachments/assets/ffe8bff7-a18f-465b-935e-51dd0b0bcec0)

### Payment section before
![image](https://github.com/user-attachments/assets/a417151c-4a14-4ae3-940a-1ff7a405f230)
### Payment section after
![image](https://github.com/user-attachments/assets/2483d3fc-48d8-4ec9-a7cb-a27fc253e62b)

### Games section before
![image](https://github.com/user-attachments/assets/3fc74eab-90d8-49d9-8538-3eec22bd63f0)
### Games section after
![image](https://github.com/user-attachments/assets/78e6fc18-22d6-4207-891c-ee97515b0625)

### Passport section before
![image](https://github.com/user-attachments/assets/a485b3eb-c385-4853-9991-ce39a892d7a6)
### Passport section after
![image](https://github.com/user-attachments/assets/90db40b9-bb6d-48a4-a45b-20bfdcabfb28)

### Additional Information

Please review the changes and let me know if any further adjustments are needed.

2024-07-18 08:23 UTC, Poolitzer commented
Hello, thanks for the PR.

Please dont modify the gitignore. The available types change is not needed, neither do we provide json objects nor does python have 32 bit signed integers.

For the rest without looking deeply into it: Please use for linking to ours the internal links as we do in the docs. So e.g. paramref:`~telegram.Bot.local_mode` for a parameter, :attr:`telegram.Message.reply_markup` for an attribute, :meth:`telegram.Bot.set_game_score` for a method, etc.

2024-07-18 11:56 UTC, mohdyusuf2312 commented
![image](https://github.com/user-attachments/assets/07bde8f1-7231-4073-9a72-1f2ef68a9170)

I'm trying to apply internal linking, but it is not clickable. Can you please suggest how I can resolve this?

2024-07-18 17:49 UTC, Bibo-Joshi commented
Hi. the linking is case sensitive, i.e. <code>:class:\`telegram.Game\`</code> can work, but <code>:class:\`Telegram.Game\`</code> can not. If you want to link to a headline, it should be possible to use the headline as lower case and "-" instead of " " as target - e.g. <code>:ref:\`inline-mode\`</code> for a headline "Inline Mode". I'm not 100% sure on this one though.
Additionally, when you build the documentation in the command line, you will see warnings and errors being printed for references that could not be resolved.
If you're new to documentation python code with Sphinx, please also have a look at their [documentation](https://www.sphinx-doc.org/en/master/), especiall at the [rst primer](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html) and the [referencing syntax](https://www.sphinx-doc.org/en/master/usage/referencing.html).

2024-07-18 20:26 UTC, mohdyusuf2312 commented
> If you're new to documentation python code with Sphinx, please also have a look at their [documentation](https://www.sphinx-doc.org/en/master/), especiall at the [rst primer](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html) and the [referencing syntax](https://www.sphinx-doc.org/en/master/usage/referencing.html).
Thanks @Bibo-Joshi Sir

2024-07-21 18:51 UTC, Bibo-Joshi requested changes
Thanks for the updates. I left a few comments. In addition, what's still missing is making the "more about" links ponit to the PTB docs rather than TG docs as explained in #4380, e.g. https://github.com/python-telegram-bot/python-telegram-bot/blob/422993b8ab05d49dd49ab58c500f880918d894a7/telegram/_reply.py#L95

2024-07-21 18:51 UTC, Bibo-Joshi commented on docs/source/telegram.games-tree.rst
> +Your bot can offer users **HTML5 games** to play solo or to compete against each other in groups and one-on-one chats. Create games via `@BotFather <https://telegram.me/BotFather>`_ using the /*newga
`/*newgame*` will not render correctly. Please use <code>\`\`/newgame\`\`</code> to ensure that it's rendered as mono-spaced text.

2024-07-21 18:51 UTC, Bibo-Joshi commented on docs/source/telegram.games-tree.rst
> +* Games are a new type of content on Telegram, represented by the :doc:`Game <telegram.game>` and :doc:`InlineQueryResultGame <telegram.inlinequeryresultgame>` objects.
<code>:doc:\`Game <telegram.game>\`</code>

This is better, but is has two downsides:

* by using `:doc:`, Sphinx doesn't know that you're referencing a class. Indexing and rendering might be wrong. Please use `:class:` for classes `:meth:` for methods of classes etc. The available types are listed at https://www.sphinx-doc.org/en/master/usage/domains/python.html#python-xref-roles (drop the leading `:py`) and are also used throughout the PTB documentation
* you make your live harder by repeating "game" twice. If you write just <code>:class:\`telegram.Game\`</code> you aovid duplication and have correcting rendering.

2024-07-21 18:51 UTC, Bibo-Joshi commented on docs/source/telegram.inline-tree.rst
> +The following methods and objects allow your bot to work in `inline mode`_.
where does this link point to? Please make sure it points to https://core.telegram.org/bots/inline as it does in https://core.telegram.org/bots/api#inline-mode.

2024-07-21 18:51 UTC, Bibo-Joshi commented on docs/source/telegram.inline-tree.rst
> +Please see our `Introduction to Inline bots <https://core.telegram.org/bots/inline>`_ for more details.
```suggestion
Please see Telegrams `Introduction to Inline bots <https://core.telegram.org/bots/inline>`_ for more details.
```
kindly double check your changes for this kind of reference. We should make sure that with "we" we always mean PTB.

2024-07-21 18:51 UTC, Bibo-Joshi commented on docs/source/telegram.inline-tree.rst
> +To enable this option, send the /setinline command to `@BotFather <https://t.me/botfather>`_ and provide the placeholder text that the user will see in the input field after typing your bot's name.
```suggestion
To enable this option, send the ``/setinline`` command to `@BotFather <https://t.me/botfather>`_ and provide the placeholder text that the user will see in the input field after typing your bot's name.
```

2024-07-22 12:18 UTC, mohdyusuf2312 commented
Hello, is everything done, or should I do anything else?

2024-07-22 19:57 UTC, Bibo-Joshi requested changes

2024-07-22 19:57 UTC, Bibo-Joshi commented on telegram/_message.py
> +            `More about games >> <https://docs.python-telegram-bot.org/telegram.games-tree.html>`_.
These should also work with sphinxs reference system. I guess <code>:ref:\`More about games >> \<games\>\`</code> should work, or `:doc:`. If you can not get the link to point to the correct location, you might need to introduce a refrence target manually - I'm sure that your favorite search engine will help you with that :)

2024-07-22 19:57 UTC, Bibo-Joshi commented on docs/source/telegram.games-tree.rst
> +* A game message will also display high scores for the current chat. Use setGameScore to post high scores to the chat with the game, add the ``edit_message`` parameter to automatically update the mes
```suggestion
* A game message will also display high scores for the current chat. Use :meth:`~telegram.Bot.set_game_score` to post high scores to the chat with the game, add the :paramref:`~telegram.Bot.set_game_score.paramref.edit_message` parameter to automatically update the message with the current scoreboard.
```

and similar in other places if you see any :)

2024-07-24 18:43 UTC, Bibo-Joshi approved these changes
Added two small fixes that are not you're fault (see https://github.com/tdlib/telegram-bot-api/issues/617).
LGTM now. Thanks very much for the PR and your patience during the review process :)

2024-07-24 19:02 UTC, merged

2024-07-25 06:09 UTC, mohdyusuf2312 commented
Thank you sir, I feel very happy to complete my first contribution to open source. :)