[Draft] Prepare for Py +3.9 support
python-telegram-bot/python-telegram-bot pull request #4398
Opened 2024-07-22 14:17 UTC by elpekenin

As per title, so far:
- Mass search+replace for stuff like `List`->`list`
- Silence warnings, while no better solution is found, for `Type[UT]`
- Update usages of deprecated `typing.AsyncContextManager`
- Update `3.8` to `3.9` in `pyproject.toml`
- Use `str.removeprefix` (i might have missed a couple of places doing the same logic manually)

2024-10-09 01:34 UTC, harshil21 commented
@elpekenin Python 3.8 reached EoL yesterday and 3.13 final was released. Do you want to still work on this or should we pick it up again?

2024-10-09 05:26 UTC, elpekenin commented
Will (try and) take a look later today

2024-10-21 17:59 UTC, Bibo-Joshi requested changes
Heyho. I've scrolled through the changes a bit, but didn't see anything besides the two comments below. @elpekenin what'sy our status on this PR otherwise? I see that it's still marked as draft.

2024-10-21 17:59 UTC, Bibo-Joshi commented on telegram/ext/_utils/_update_parsing.py
> +def parse_username(username: Optional[SCT[str]]) -> frozenset[str]:
this function can also make use of `removeprefix` :)

2024-10-21 17:59 UTC, Bibo-Joshi commented on telegram/ext/_handlers/typehandler.py
> +        type: GenericUT,  # pylint: disable=redefined-builtin
the type completeness check is not happy with this. Maybe it needs to be `GenericUT[UT]`? 🤔

2024-10-23 20:08 UTC, Bibo-Joshi approved these changes
@elpekenin @harshil21 if I don't hear vehement disagreement from you, I'll merge some time on the weekend :)

2024-10-23 20:39 UTC, harshil21 approved these changes

2024-10-23 21:13 UTC, elpekenin commented
Sorry for the silence, somehow i didnt get/set notifications about the feedback.

I have no idea what `GenericUT[UT]` is supposed to mean. From my understanding, * We wouldnt need an alias for the hint
* Would just use `Type[UT]` in there (uppercase just because tooling might get confused with `type` also being the name of the variable)
* Referencing `UT` outside function would be the same as using `Any` as it is not bound by the specific callers' typing (?) 
... But its been such a headache trying stuff without any success that im fine with anything that tooling like :P

2024-10-24 10:33 UTC, Bibo-Joshi commented
> But its been such a headache trying stuff without any success that im fine with anything that tooling like :P

Its certainly weird 😅 my last commit seemed to work and I also checked that `reveal_type` produces sane output with both mypy and pyright, so it would be goos enough for me :D

2024-10-24 18:48 UTC, merged

2024-10-24 18:48 UTC, Bibo-Joshi commented
Thank you very much for the contribution :)