Api 7.10 Paid media payload and Giveaway updates.
python-telegram-bot/python-telegram-bot pull request #4463
Opened 2024-09-08 09:51 UTC by aelkheir

Closes #4459
- [x] Added the ability to specify a payload in [sendPaidMedia](https://core.telegram.org/bots/api#sendpaidmedia) that is received back by the bot in [TransactionPartnerUser](https://core.telegram.org/bots/api#transactionpartneruser) and purchased_paid_media updates. (Taken by @aelkheir)
- [x] Added the field prize_star_count to the classes [GiveawayCreated](https://core.telegram.org/bots/api#giveawaycreated), [Giveaway](https://core.telegram.org/bots/api#giveaway), [GiveawayWinners](https://core.telegram.org/bots/api#giveawaywinners) and [ChatBoostSourceGiveaway](https://core.telegram.org/bots/api#chatboostsourcegiveaway).  (Taken by @aelkheir)
- [x] Added the field is_star_giveaway to the class [GiveawayCompleted](https://core.telegram.org/bots/api#giveawaycompleted).  (Taken by @aelkheir)

## Checklist for PRs
- [x] Added ``.. versionadded:: NEXT.VERSION``, ``.. versionchanged:: NEXT.VERSION``, ``.. deprecated:: NEXT.VERSION`` or ``.. versionremoved:: NEXT.VERSION`` to the docstrings for user facing changes (for methods/class descriptions, arguments and attributes)
- [x] Created new or adapted existing unit tests
- [ ] Documented code changes according to the `CSI standard <https://standards.mousepawmedia.com/en/stable/csi.html>`__
- [ ] Added myself alphabetically to ``AUTHORS.rst`` (optional)
- [ ] Checked the `Stability Policy <https://docs.python-telegram-bot.org/stability_policy.html>`_ in case of deprecations or changes to documented behavior

**If the PR contains API changes (otherwise, you can ignore this passage)**
- [ ] Checked the Bot API specific sections of the `Stability Policy <https://docs.python-telegram-bot.org/stability_policy.html>`_
- [ ] Created a PR to remove functionality deprecated in the previous Bot API release (`see here <https://docs.python-telegram-bot.org/en/stable/stability_policy.html#case-2>`_)
-  New classes:
   - [x] Added ``self._id_attrs`` and corresponding documentation
   - [x] ``__init__`` accepts ``api_kwargs`` as kw-only
-  Added new shortcuts:
   - [x] In :class:`~telegram.Chat` & :class:`~telegram.User` for all methods that accept ``chat/user_id``
-  If relevant:
   - [x] Link new and existing constants in docstrings instead of hard-coded numbers and strings
   - [x] Added or updated documentation for the changed class(es) and/or method(s)

2024-09-08 12:56 UTC, Bibo-Joshi commented on tests/test_giveaway.py
> +
a test_equality test would be needed for new rich equality comparison :)

2024-09-08 13:06 UTC, Bibo-Joshi commented on telegram/_chatboost.py
>      The boost was obtained by the creation of a Telegram Premium giveaway. This boosts the chat 4
```suggestion
    The boost was obtained by the creation of a Telegram Premium or a Telegram Star giveaway. This boosts the chat 4
```

2024-09-08 13:25 UTC, aelkheir commented on telegram/_giveaway.py
> +
even though the new param is optional?

2024-09-08 21:02 UTC, harshil21 requested changes
just doc fixes

2024-09-09 05:08 UTC, harshil21 approved these changes

2024-09-09 20:03 UTC, Bibo-Joshi reviewed
was left hanging in pending …

2024-09-09 20:33 UTC, merged

2024-09-09 20:34 UTC, Bibo-Joshi commented
Thank you a lot for the nice and fast PR!