feat: add `show_caption_above_media` parameter to `(Ext)Defaults`
python-telegram-bot/python-telegram-bot pull request #4520
Opened 2024-10-07 19:34 UTC by servusdei2018

Fixes #4306

## Summary

This patch introduces a default setting for the `show_caption_above_media` parameter in the `telegram.ext.Defaults` class. This enhancement streamlines the process of setting this parameter across various bot methods that support it, such as `send_video`, `send_photo`, and `edit_message_caption`.

## Changes Made

- A new property `show_caption_above_media` has been added to the `(Ext)Bot` class.

2024-10-08 22:11 UTC, servusdei2018 commented
cc @Poolitzer @Bibo-Joshi

2024-10-08 23:07 UTC, Bibo-Joshi commented
Hi. Thanks for your PR. There is no need to ping us. We will reply when we have the time.

2024-10-21 18:07 UTC, Bibo-Joshi requested changes
Hi. Please see my comments below. Also, be sure that you have read our [contribution guide](https://docs.python-telegram-bot.org/en/v21.6/contributing.html) and include the check list in the PR description.

2024-10-21 18:07 UTC, Bibo-Joshi commented on telegram/ext/_defaults.py
> +        shown above the media. Defaults to `None`.
```suggestion
            shown above the media. Defaults to `None`.
```

2024-10-21 18:07 UTC, Bibo-Joshi commented on telegram/ext/_extbot.py
this is not how we implement Defaults. Please have a look at the methods `_insert_defaults` and `_insert_defaults_for_ilq_results`. Note that changes will also be necessary for `Bot`. Finally, we will need new unit tests for this.

2024-10-30 20:22 UTC, krishna931074 commented
Stranger

2024-11-04 19:29 UTC, Bibo-Joshi commented
closing due to inactivity. @servusdei2018 feel free to reopen anytime if you want to continue working on this

2024-11-04 19:29 UTC, closed without merging