Unifiy datetime import in all files
python-telegram-bot/python-telegram-bot pull request #4605
Opened 2024-12-13 03:11 UTC by cuevasrja

# Unifiy datetime import in all files

@Jeam-zx
@Migueldsc12
@AnyaMarcanito
@henryg311
@cuevasrja

## Summary

Convert all datetime imports of the project to `import datetime as dtm`. Since there was no standard in importing functions from this library.

## Tests

It was verified that all changes passed the static check performed by the linters and other project tools with the `pre-commit run -a` command.

## Check-list

This checklist is a non-exhaustive reminder of things that should be done before a PR is merged, both for you as contributor and for the maintainers. Feel free to copy (parts of) the checklist to the PR description to remind you or the maintainers of open points or if you have questions on anything.

- [x] Added .. versionadded:: NEXT.VERSION, .. versionchanged:: NEXT.VERSION, .. deprecated:: NEXT.VERSION or .. versionremoved:: NEXT.VERSION to the docstrings for user facing changes (for methods/class descriptions, arguments and attributes) 
- [x] Created new or adapted existing unit tests 
- [x] Documented code changes according to the [CSI standard](https://standards.mousepawmedia.com/en/stable/csi.html)
- [x] Added myself alphabetically to AUTHORS.rst (optional)
- [x] Added new classes & modules to the docs and all suitable __all__ s
- [x] Checked the [Stability Policy](https://docs.python-telegram-bot.org/stability_policy.html) in case of deprecations or changes to documented behavior

## Issue

Resolves #4577

2024-12-13 03:53 UTC, cuevasrja commented on telegram/constants.py
Thank you, but it continues failing in some Python Versions

2024-12-13 19:25 UTC, Bibo-Joshi requested changes
Thank you very much for the PR!
I just found two additional `import datetime` s in `test_jobqueue` and `test_businessmessagesdeletedhandler`, otherwise LGTM :)

2024-12-14 16:11 UTC, Bibo-Joshi requested changes
Thanks for the update! Now unfortunately something went wrong with merging master: Apparently you reverted the merge in https://github.com/python-telegram-bot/python-telegram-bot/pull/4605/commits/dda1e7ca1be439de94aac643457291ca3b7dad13 - please revert the revert 😅

2024-12-15 09:24 UTC, Bibo-Joshi approved these changes

2024-12-15 09:26 UTC, merged

2024-12-15 09:26 UTC, Bibo-Joshi commented
Thank you very much for the contribution :)